# Generated by Django 6.0.2 on 2026-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor_approved',
            field=models.BooleanField(default=False, help_text='Admin approval for vendor account'),
        ),
    ]
