# Generated by Django 6.0.2 on 2026-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor_rejected',
            field=models.BooleanField(default=False, help_text='Admin explicitly rejected this vendor application'),
        ),
    ]
