# Generated by Django 6.0.2 on 2026-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('trekking', 'Trekking'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('pilgrimage', 'Pilgrimage')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenuous', 'Strenuous')], max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('best_season', models.CharField(max_length=100)),
                ('max_altitude', models.PositiveIntegerField(help_text='Maximum altitude in meters')),
                ('starting_price', models.DecimalField(decimal_places=2, help_text='Starting price in USD', max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='trips/')),
                ('highlights', models.JSONField(default=list)),
                ('itinerary_days', models.JSONField(default=list)),
                ('included_services', models.JSONField(default=list)),
                ('excluded_services', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trip_templates',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['category'], name='trip_templa_categor_7db201_idx'), models.Index(fields=['difficulty'], name='trip_templa_difficu_42fccd_idx'), models.Index(fields=['slug'], name='trip_templa_slug_d8f39b_idx')],
            },
        ),
    ]
