# Generated by Django 6.0.2 on 2026-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_booking_admin_notes_booking_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to='vehicles/'),
        ),
    ]
