# Generated by Django 6.0.2 on 2026-03-22 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_merge_0003_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's counter-offer per day", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price per day after negotiation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_expires_at',
            field=models.DateTimeField(blank=True, help_text='48-hour deadline for negotiation response', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_status',
            field=models.CharField(choices=[('none', 'None'), ('customer_offered', 'Customer Offered'), ('vendor_countered', 'Vendor Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vendor's original listed price (preserved for transparency)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_negotiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_counter_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vendor's counter-offer per day", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_vendor_approval', 'Pending Vendor Approval'), ('pending_customer_approval', 'Pending Customer Approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('vehicle_condition_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_behavior_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='marketplace.booking')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('vehicle_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='marketplace.vehiclelisting')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor'], name='ratings_vendor__2c9146_idx'), models.Index(fields=['vehicle_listing'], name='ratings_vehicle_e43888_idx')],
            },
        ),
    ]
