# Generated by Django 6.0.2 on 2026-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_booking_customer_offered_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('jeep', 'Jeep'), ('hiace', 'Hiace/Van'), ('coaster', 'Coaster'), ('bus', 'Bus')], max_length=20),
        ),
    ]
